<Project>
  <!-- Public API analyzers for source projects only -->
  <ItemGroup Condition="$(MSBuildProjectDirectory.Contains('src'))">
    <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" PrivateAssets="all" />
  </ItemGroup>

  <!-- MinVer for source projects only -->
  <ItemGroup Condition="$(MSBuildProjectDirectory.Contains('src'))">
    <PackageReference Include="MinVer" PrivateAssets="all" />
  </ItemGroup>
</Project>
